[workspace]
resolver = "3"
members = ["browser"]

[workspace.package]
edition = "2024"

[package]
name = "f1stmux"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "f1stmux"
path = "src/main.rs"

[lib]
name = "f1stmux"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13", default-features = false, features = ["http2", "socks", "rustls-no-provider", "brotli", "gzip", "charset"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
webpki-roots = "1"
rquickjs = { version = "0.14", features = ["bindgen", "loader"] }
html5ever = "0.39"
markup5ever_rcdom = "0.39"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding_rs = "0.8"
clap = { version = "4", features = ["derive", "env"] }
regex = "1"
base64 = "0.22"
rand = "0.8"
f1stchrome = { version = "0.1.0", path = "browser" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
